import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'text-body': '#334155',
        'surface-bright': '#f8f9ff',
        'primary': '#00236f',
        'on-surface': '#0b1c30',
        'status-success-bg': '#ECFDF5',
        'surface-container': '#e5eeff',
        'tertiary-fixed-dim': '#bec6e0',
        'surface-container-low': '#eff4ff',
        'outline-variant': '#c5c5d3',
        'border-subtle': '#E2E8F0',
        'on-tertiary-fixed-variant': '#3f465c',
        'canvas': '#F8FAFC',
        'on-tertiary-fixed': '#131b2e',
        'surface-variant': '#d3e4fe',
        'on-primary-container': '#90a8ff',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#a4acc5',
        'tertiary-container': '#384055',
        'tertiary': '#222a3e',
        'on-error-container': '#93000a',
        'secondary-container': '#316bf3',
        'secondary': '#0051d5',
        'surface': '#FFFFFF',
        'background': '#f8f9ff',
        'tertiary-fixed': '#dae2fd',
        'error': '#ba1a1a',
        'text-secondary': '#64748B',
        'surface-subtle': '#F1F5F9',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#fefcff',
        'primary-container': '#1e3a8a',
        'on-tertiary': '#ffffff',
        'text-muted': '#94A3B8',
        'secondary-fixed-dim': '#b4c5ff',
        'surface-tint': '#4059aa',
        'text-primary': '#0F172A',
        'surface-container-high': '#dce9ff',
        'outline': '#757682',
        'status-error': '#DC2626',
        'status-flag': '#F97316',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#b6c4ff',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'status-flag-bg': '#FFF7ED',
        'primary-fixed': '#dce1ff',
        'inverse-surface': '#213145',
        'border-strong': '#CBD5E1',
        'surface-container-highest': '#d3e4fe',
        'status-error-bg': '#FEF2F2',
        'on-background': '#0b1c30',
        'on-surface-variant': '#444651',
        'secondary-fixed': '#dbe1ff',
        'on-secondary-fixed-variant': '#003ea8',
        'on-primary-fixed-variant': '#264191',
        'surface-dim': '#cbdbf5',
        'primary-fixed-dim': '#b6c4ff',
        'on-primary-fixed': '#00164e',
        'on-secondary-fixed': '#00174b',
        'status-success': '#059669',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'margin-desktop': '2rem',
        'gutter': '1rem',
        'gutter-desktop': '1.5rem',
        'space-lg': '1.5rem',
        'margin': '1rem',
        'space-xs': '0.25rem',
        'space-xl': '2rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-reading': ['Inter', 'sans-serif'],
        'numeric-timer': ['Inter', 'sans-serif'],
        'headline-xl-mobile': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'caption': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'numeric-metric': ['Inter', 'sans-serif'],
        'body-default': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-reading': ['15px', { lineHeight: '25px', fontWeight: '400' }],
        'numeric-timer': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-xl-mobile': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'caption': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-xl': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'numeric-metric': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-default': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'label-sm': ['13px', { lineHeight: '18px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};

export default config;
