SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE question;
TRUNCATE TABLE question_group;
TRUNCATE TABLE part;
TRUNCATE TABLE exam;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO exam (id, code, title, category, duration_minutes, total_questions, is_published, created_at) VALUES 
(1, 'ETS2023_01', 'ETS 2023 TEST 01 Reading', 'READING', 75, 100, 1, NOW());

INSERT INTO part (id, exam_id, name, part_number, total_questions) VALUES 
(5, 1, 'Part 5: Incomplete Sentences', 5, 30),
(6, 1, 'Part 6: Text Completion', 6, 16),
(7, 1, 'Part 7: Reading Comprehension', 7, 54);

-- Part 5: 30 câu hỏi hoàn chỉnh (101 - 130)
INSERT INTO question (question_number, content, option_a, option_b, option_c, option_d, correct_option, explanation, part_id) VALUES
(101, 'When she held her last meeting, Ms. Toba ------- her sales staff to perform even better next quarter.', 'encourage', 'is encouraging', 'encouraged', 'was encouraged', 'C', 'Hành động xảy ra trong quá khứ (\"held\"), chia thì quá khứ đơn chủ động.', 5),
(102, 'All staff have been informed ------- the proposed partnership with ERI Finance.', 'for', 'about', 'to', 'at', 'B', 'Cụm từ cố định: inform someone about/of something (thông báo về việc gì).', 5),
(103, 'On Friday, Mr. Nakamura will discuss ------- ideas for supporting busy waiters.', 'his', 'him', 'himself', 'he', 'A', 'Cần một tính từ sở hữu đứng trước danh từ \"ideas\".', 5),
(104, 'The Forestry Commission was created to ------- the state\'s natural resources and wildlife.', 'allow', 'manage', 'succeed', 'finish', 'B', 'Xét nghĩa: \"manage\" (quản lý tài nguyên thiên nhiên và động vật hoang dã).', 5),
(105, 'By following established guidelines, construction workers will be able to complete their tasks -------.', 'safety', 'safe', 'safeness', 'safely', 'D', 'Cần một trạng từ (safely) để bổ nghĩa cho động từ \"complete\".', 5),
(106, 'With her numerous credentials, Dr. Kwan is highly ------- to teach medieval history at Maston University.', 'arranged', 'ready', 'available', 'qualified', 'D', 'Cụm tính từ: highly qualified to do something (đủ trình độ/chuyên môn cao).', 5),
(107, '------- at the annual technology conference is mandatory for all engineers at the Treemont Corporation.', 'Attendance', 'Attend', 'Attends', 'Attended', 'A', 'Cần một danh từ (Attendance) đóng vai trò làm chủ ngữ của câu.', 5),
(108, 'The café ------- features poets, folk singers, and drama groups on its stage.', 'tightly', 'occasionally', 'vaguely', 'realistically', 'B', 'Xét nghĩa trạng từ chỉ tần suất: \"occasionally\" (thỉnh thoảng/đôi khi).', 5),
(109, 'Before the seminar began, attendees were assured ------- all scheduled presenters would appear.', 'who', 'around', 'that', 'therefore', 'C', 'Cấu trúc mệnh đề danh từ: be assured that + mệnh đề (được đảm bảo rằng).', 5),
(110, 'Forever Pet has been a leader in bringing new products, ------- Fun Bone and Chew Right, to the market.', 'however', 'furthermore', 'as if', 'such as', 'D', 'Dùng \"such as\" để đưa ra ví dụ minh họa.', 5),
(111, 'Ms. Turner is in charge of ------- the organization of records in the human services department.', 'improve', 'improved', 'improving', 'improvement', 'C', 'Sau giới từ \"of\" cần V-ing (\"improving\") vì phía sau có tân ngữ \"the organization\".', 5),
(112, 'Sheefon Bank clients always receive an e-mail or text ------- following any change to their account password.', 'issue', 'alert', 'claim', 'member', 'B', 'Cụm danh từ: \"text alert\" (thông báo/cảnh báo bằng tin nhắn văn bản).', 5),
(113, 'A drop in consumer demand has led to a ------- decrease in the production of large pickup trucks.', 'remark', 'remarked', 'remarking', 'remarkable', 'D', 'Cần tính từ \"remarkable\" (đáng kể) đứng trước danh từ \"decrease\".', 5),
(114, 'After coating the potatoes in flour and spices, chefs should place them ------- into the deep fryer.', 'rarely', 'honestly', 'doubtfully', 'directly', 'D', 'Xét nghĩa trạng từ: \"directly into\" (cho trực tiếp vào).', 5),
(115, 'Several banks have released applications that allow customers to pay bills ------- easily by phone.', 'their', 'they', 'them', 'themselves', 'D', 'Đại từ phản thân \"themselves\" dùng để nhấn mạnh khách hàng tự thanh toán hóa đơn.', 5),
(116, 'The personnel department will ------- only those applicants who have five or more years of experience for the position.', 'participate', 'consider', 'grant', 'make', 'B', 'Xét nghĩa ngoại động từ: \"consider\" (xem xét/cân nhắc các ứng viên).', 5),
(117, 'Employees of Belfore Electronics Ltd. are ------- involved in community-assistance programs.', 'active', 'actively', 'activate', 'activity', 'B', 'Cần trạng từ \"actively\" để bổ nghĩa cho tính từ/phân từ \"involved\".', 5),
(118, 'The executives at Macalter Equipment decided they would not ------- the contract without major changes.', 'renew', 'consume', 'identify', 'resemble', 'A', 'Cụm từ xét theo ngữ cảnh: \"renew the contract\" (gia hạn hợp đồng).', 5),
(119, 'Wet suits are made with a ------- layer of rubber that traps heat and keeps divers warm.', 'protect', 'protects', 'protective', 'protectively', 'C', 'Cần tính từ \"protective\" (bảo vệ) đứng trước danh từ \"layer\".', 5),
(120, 'Newcamp Services managers will meet to discuss the proposed ------- of three smaller branches into one large branch.', 'security', 'bracket', 'connector', 'merger', 'D', 'Xét nghĩa: \"merger\" (sự sáp nhập 3 chi nhánh nhỏ thành 1 chi nhánh lớn).', 5),
(121, 'At Yarzen Technology, clients\' records are ------- and can only be accessed by a small group of fund managers.', 'confide', 'confidential', 'confidentially', 'confidentiality', 'B', 'Sau động từ to-be \"are\" cần tính từ \"confidential\" (bảo mật).', 5),
(122, 'The featured panel at the NHJ Medical Conference will discuss recent ------- in online health-care services.', 'memories', 'varieties', 'trends', 'rehearsals', 'C', 'Xét nghĩa: \"recent trends\" (các xu hướng gần đây trong dịch vụ chăm sóc sức khỏe trực tuyến).', 5),
(123, 'All of Millville\'s restaurants ------- several times a year by the city health department.', 'inspect', 'inspected', 'are inspecting', 'are inspected', 'D', 'Câu bị động ở thì hiện tại đơn chỉ hành động lặp đi lặp lại: \"are inspected\".', 5),
(124, 'Sweet Sunlight Bakery has steadily built a ------- base of customers with its delicious cookies and cakes.', 'brief', 'loyal', 'strict', 'careful', 'B', 'Cụm từ phổ biến: \"loyal base of customers\" (tập khách hàng trung thành).', 5),
(125, 'According to financial analysts, ------- in medical technology companies are expected to increase in value.', 'invest', 'investing', 'invested', 'investments', 'D', 'Cần danh từ số nhiều \"investments\" (các khoản đầu tư) làm chủ ngữ cho động từ \"are\".', 5),
(126, 'The city\'s harbor is ------- to container ships and fishing vessels of all sizes.', 'accessible', 'formal', 'reasonable', 'likely', 'A', 'Cấu trúc: \"accessible to\" (có thể tiếp cận được đối với tàu thuyền mọi kích cỡ).', 5),
(127, 'Maya\'s Dancewear expanded its advertising markets, and sales have ------- increased.', 'controlling', 'consequently', 'beneath', 'even though', 'B', 'Trạng từ liên kết chỉ kết quả: \"consequently\" (kết quả là/do đó).', 5),
(128, 'Dobson Ice Cream will not introduce any new flavors ------- the customer survey results are analyzed.', 'around', 'until', 'despite', 'past', 'B', 'Cấu trúc: not... until (sẽ không giới thiệu hương vị mới cho đến khi kết quả được phân tích).', 5),
(129, 'The renovated company gym ------- with free weights and exercise machines.', 'will equip', 'to equip', 'has been equipped', 'is equipping', 'C', 'Dạng bị động hoàn thành: phòng tập \"đã được trang bị\" thiết bị tập luyện.', 5),
(130, '------- driving their cars, workers who travel to the town center should use the bus lines.', 'Because of', 'Instead of', 'Whenever', 'Although', 'B', 'Giới từ chỉ sự thay thế: \"Instead of + V-ing\" (thay vì lái xe ô tô).', 5);

-- Part 6: 4 Question Groups & 16 Câu hỏi hoàn chỉnh (131 - 146)
INSERT INTO question_group (id, part_id, passage_text) VALUES 
(1, 6, 'MALENDA COUNTY (January 12) - Pat and Kenny''s Barbershop, [131] at 3949 Grand Street, has been named the best barbershop in the state by the Barber and Hairdresser''s Coalition. The criteria for selection include reputation, affordability, professionalism, and accreditations. [132].\n\nFounders and owners Kenneth Webber and Patrick Miller have been best friends since childhood. [133] opened the shop 34 years ago. [134] the shop retains its old-fashioned charm, the barbers have mastered the latest styles, not just the more traditional ones. People of all ages seeking a haircut or a new style should try Pat and Kenny''s Barbershop.'),
(2, 6, 'Gasgo Propane Tank Exchange\n\nThank you for purchasing a Gasgo propane tank. You have chosen a safe and [135] way to obtain fuel for your stoves, grills, heaters, fireplaces, or other devices.\n\nSimply follow the directions [136]. When your tank runs out of propane, take it to our store and leave it on one of the clearly marked green shelves outside the store. [137] Then, pay the cashier inside the store for a fresh tank of propane.\n\nBe sure to visit us again when you need a [138].'),
(3, 6, 'To: Technicarn Enterprises Customers\nFrom: Customer Support\nDate: October 14\nSubject: New and Improved Web Site\n\nWe want your [139] with Technicarn Enterprises to be easy and enjoyable. We have recently redesigned our Web site to serve you better.\n\nOn our home page, you can get information about system setup, or you can troubleshoot by visiting [140] the Internet Issues or TV and Streaming Issues pages. [141], you can find detailed information concerning account management, access, billing, and payment.\n\n[142] Please explore the new Web site at your earliest convenience: www.technicarnenterprises.com.'),
(4, 6, 'Garner City Transport Cares About the Environment\n\nBeginning May 1, the sale and use of paper tickets and transit passes will be [143] on all Garner City Transport bus and subway lines. This change applies to single-ride tickets [144] weekly and monthly passes.\n\nGarner City Transport encourages riders to use the new mobile app. With the app, they can add money to their accounts, purchase tickets, plan [145], and track arrival and departure times.\n\nAlternatively, passengers can purchase a rechargeable transit card at any station. [146] Value can be added to the card via the Garner City Transport Web site at www.garnercitytransport.org.');

INSERT INTO question (question_number, content, option_a, option_b, option_c, option_d, correct_option, explanation, part_id, question_group_id) VALUES 
-- Đoạn 1 (131 - 134)
(131, 'Pat and Kenny\'s Barbershop, ------- at 3949 Grand Street, has been named the best barbershop in the state by the Barber and Hairdresser\'s Coalition.', 'locate', 'located', 'locates', 'location', 'B', 'Mệnh đề quan hệ rút gọn ở dạng bị động: \"which is located at...\" rút gọn thành \"located at...\".', 6, 1),
(132, 'The criteria for selection include reputation, affordability, professionalism, and accreditations. [-------]', 'The results will be announced later this month.', 'We are proud to serve our community with excellence.', 'Pat and Kenny\'s shop excelled in all four categories.', 'Please call in advance to schedule an appointment.', 'C', 'Câu phía trước nhắc đến 4 tiêu chí lựa chọn, do đó câu tiếp nối hợp lý nhất là khẳng định tiệm đã xuất sắc ở cả 4 tiêu chí đó.', 6, 1),
(133, 'Founders and owners Kenneth Webber and Patrick Miller have been best friends since childhood. ------- opened the shop 34 years ago.', 'I', 'We', 'They', 'He', 'C', 'Đại từ nhân xưng thay thế cho hai người đồng sáng lập (Kenneth Webber và Patrick Miller) là \"They\".', 6, 1),
(134, '------- the shop retains its old-fashioned charm, the barbers have mastered the latest styles, not just the more traditional ones.', 'While', 'Despite', 'Even', 'Yet', 'A', 'Dùng liên từ \"While\" (mặc dù) để chỉ sự tương phản giữa 2 mệnh đề: dù vẫn giữ nét cổ điển nhưng thợ cắt tóc đã làm chủ các phong cách mới nhất.', 6, 1),
-- Đoạn 2 (135 - 138)
(135, 'You have chosen a safe and ------- way to obtain fuel for your stoves, grills, heaters, fireplaces, or other devices.', 'economy', 'economics', 'economize', 'economical', 'D', 'Cần một tính từ song hành với \"safe\" đứng trước danh từ \"way\": \"economical\" (tiết kiệm/kinh tế).', 6, 2),
(136, 'Simply follow the directions -------.', 'below', 'finally', 'sometimes', 'hourly', 'A', 'Chỉ dẫn xuất hiện ở phần văn bản ngay phía dưới nên dùng trạng từ/giới từ chỉ vị trí: \"the directions below\" (hướng dẫn bên dưới).', 6, 2),
(137, 'When your tank runs out of propane, take it to our store and leave it on one of the clearly marked green shelves outside the store. [-------] Then, pay the cashier inside the store for a fresh tank of propane.', 'Come again very soon.', 'It is warmer in the store.', 'Do not take it inside.', 'The tank is prefilled.', 'C', 'Quy tắc an toàn khi đổi bình gas: để ở kệ bên ngoài cửa hàng và \"Không mang bình vào bên trong\" trước khi vào quầy thanh toán.', 6, 2),
(138, 'Be sure to visit us again when you need a -------.', 'model', 'version', 'heater', 'replacement', 'D', 'Ngữ cảnh đổi bình gas khi hết: ghé thăm lại khi bạn cần một bình thay thế (\"replacement\").', 6, 2),
-- Đoạn 3 (139 - 142)
(139, 'We want your ------- with Technicarn Enterprises to be easy and enjoyable.', 'experience', 'experienced', 'experiencing', 'experiential', 'A', 'Sau tính từ sở hữu \"your\" cần một danh từ: \"experience\" (trải nghiệm của bạn).', 6, 3),
(140, 'On our home page, you can get information about system setup, or you can troubleshoot by visiting ------- the Internet Issues or TV and Streaming Issues pages.', 'either', 'both', 'rather', 'each', 'A', 'Cấu trúc tương quan đi kèm với liên từ \"or\": \"either A or B\".', 6, 3),
(141, '-------, you can find detailed information concerning account management, access, billing, and payment.', 'Therefore', 'Regardless', 'For example', 'Moreover', 'D', 'Trạng từ liên kết bổ sung thông tin thêm về các tiện ích trên trang web: \"Moreover\" (Hơn thế nữa/Ngoài ra).', 6, 3),
(142, '[-------] Please explore the new Web site at your earliest convenience: www.technicarnenterprises.com.', 'We also need to inform you that your payment is five days past due.', 'We recommend that you purchase all related accessories in our retail store.', 'If you get an error message, disconnect from the Internet and try again.', 'If you cannot find what you need online, simply call our support number.', 'D', 'Đoạn văn giới thiệu các tiện ích trực tuyến, câu kết cung cấp phương án hỗ trợ dự phòng: nếu không tìm thấy trên mạng hãy gọi tổng đài.', 6, 3),
-- Đoạn 4 (143 - 146)
(143, 'Beginning May 1, the sale and use of paper tickets and transit passes will be ------- on all Garner City Transport bus and subway lines.', 'enlarged', 'discontinued', 'accessible', 'refreshed', 'B', 'Xét theo ngữ cảnh bảo vệ môi trường và chuyển sang ứng dụng/thẻ: vé giấy sẽ bị \"ngừng sử dụng\" (discontinued).', 6, 4),
(144, 'This change applies to single-ride tickets ------- weekly and monthly passes.', 'sharing', 'but', 'except', 'as well as', 'D', 'Cụm liên từ mang nghĩa \"cũng như\": \"as well as\" nối vé 1 lượt với vé tuần/tháng.', 6, 4),
(145, 'With the app, they can add money to their accounts, purchase tickets, plan -------, and track arrival and departure times.', 'routes', 'responses', 'software', 'careers', 'A', 'Xét chức năng của ứng dụng giao thông công cộng: \"plan routes\" (lên kế hoạch tuyến đường).', 6, 4),
(146, 'Alternatively, passengers can purchase a rechargeable transit card at any station. [-------] Value can be added to the card via the Garner City Transport Web site at www.garnercitytransport.org.', 'People often use credit cards to purchase meals during the flight.', 'Many people like public transportation because it is inexpensive.', 'The durable cards are made from recycled materials.', 'There was a small price increase last month.', 'C', 'Câu đứng giữa mô tả thêm đặc tính của thẻ giao thông sạc lại được (\"rechargeable transit card\") và phù hợp tiêu chí môi trường: thẻ bền và làm từ vật liệu tái chế.', 6, 4);

-- Part 7: 15 Question Groups & 54 Câu hỏi hoàn chỉnh (147 - 200)
INSERT INTO question_group (id, part_id, passage_text) VALUES 
-- Đoạn 1: Questions 147-148 (Advertisement)
(5, 7, 'Harbis Stationery Store Clearance Sale\n\nPrices indicated are for in-store purchases only.\n\n500 Pinstone Street / SHEFFIELD / S1 2HN\n\nSeasonal items\nBox of ten preprinted seasonal cards (25% off) - £ 8.99\nBox of five customizable seasonal cards or invitations (50% off) - £ 11.99\n\nAll school supplies 10% off\nBox of 24 pens - £ 1.79\nDesk lamp - £ 19.99\nWireless mouse - £ 17.99\nBackpack - £ 29.99\n\nVisit Harbis Stationery at www.harbisstationery.uk'),
-- Đoạn 2: Questions 149-150 (E-mail)
(6, 7, 'To: Wenbin Peng <wpeng@chenconstruction.com>\nFrom: Toshi Auto Group <cs@toshiautogroup.com>\nDate: February 26\nSubject: Your leased vehicle\n\nDear Mr. Peng:\nAs you know, Toshi Auto Group handles all the service needs for cars leased by employees of Chen Construction. According to our records, you took possession of your leased car on March 1 of last year. Your car is now due for its required annual service and maintenance check. To book your appointment, please call us at (215) 555-0109 or visit us online at www.toshiautogroup.com/serviceappointments.\n\nSincerely,\nToshi Auto Group\nCustomer Service'),
-- Đoạn 3: Questions 151-153 (Article)
(7, 7, 'LONDON (2 February) On Thursday, Tillford Press announced the launch of its new imprint, Tillford Exalt. This new line will feature books promoting healthy lifestyles, memoirs with uplifting messages, and volumes that provide guidance for special occasions such as birthdays and weddings. Tillford Exalt will also publish calendars and greeting cards that complement the main products.\n\nAlready contracted to write memoirs are the award-winning actress Alexia Leoz, London-based conductor and composer Seung-Hyun Bae, and celebrity cook Lain Lai. Ms. Lai\'s story of her life and career will be the first to be launched. It is set for release in December.\n\nTillford vice president Frederick Bissett said the company saw a need for books that celebrated accomplishments and life events from multiple perspectives. "We wanted authors from a wide variety of cultural backgrounds, and we think we\'re off to a great start," he said. He noted that Tillford Exalt\'s authors were not always famous; the books will be exploring their beginnings, their everyday lives, their first jobs, their marriages and families as well as their achievements.\n\nTillford Press is based in Manchester. It has offices in New York, Toronto, and Sydney, but its publications are sold throughout the world.'),
-- Đoạn 4: Questions 154-155 (Text-message chain)
(8, 7, 'Greg Skagen (8:58 A.M.) Hi, Brenda. I\'m here in the warehouse. All of my trainees have arrived, but I noticed the power door at Loading Dock B is acting up.\nBrenda Sadauskas (8:59 A.M.) Again?\nGreg Skagen (8:59 A.M.) When I push the button to open it, it raises all the way up but then drops back down to the closed position after about 30 seconds.\nBrenda Sadauskas (9:00 A.M.) I\'ll come down with the maintenance technicians. Why don\'t you bring your trainees to my area? You can teach them how to create shipping labels and then have them pack and label this morning\'s shipments.\nGreg Skagen (9:02 A.M.) Yes, that works.\nBrenda Sadauskas (9:03 A.M.) Thanks. Then you could show them the loading dock operations in the afternoon.'),
-- Đoạn 5: Questions 156-157 (Form)
(9, 7, 'SERVICE REQUEST FORM\nComplete all fields and deliver to Technology Services (room 412).\n\nRequester Name: Elenora Deckow\nRequester Office: Room 718\nRequester Phone: Ext. 5709\nService Location: Room 500\nService Type (choose one): [X] Repair\n\nDescription of Request:\nThere is a problem with the television audio. When I played an online video, the image was fine, but I could not hear anything. I checked all the settings, and I was able to hear the same video on other televisions with no problem. I\'m supposed to deliver a product demonstration for a client in room 500 next Monday, so I would greatly appreciate it if the issue can be fixed by this Friday.'),
-- Đoạn 6: Questions 158-161 (Text-message chain)
(10, 7, 'Ella Glatt (11:34 A.M.)\nHi. I know this is a busy day, but I wanted to know whether anyone from the finance team could come to the marketing meeting.\n\nStef Goldberg (11:35 A.M.)\nHi, Ella. I wish I could, but it starts at 2:00. I need to be at a different meeting at 2:30.\n\nElla Glatt (11:36 A.M.)\nOh, right. I forgot you were going to the executive board meeting.\n\nDaniel Seidal (11:36 A.M.)\nI\'m also supposed to go to the 2:30 meeting. Is it essential that one of us attend the marketing meeting?\n\nElla Glatt (11:37 A.M.)\nWell, it would be helpful to have someone from the finance department there, at least for 15 minutes or so.\n\nBill Iverman (11:38 A.M.)\nThe quarterly reports just came in, and Daniel, Stef, and I need to review them by the end of the day.\n\nElla Glatt (11:39 A.M.)\nYou all have plenty to do.\n\nDaniel Seidal (11:41 A.M.)\nThat\'s true! But I could come from 2:00 to 2:15. That\'s all I can commit to.\n\nElla Glatt (11:43 A.M.)\nSounds great. We just need one of you to clarify a few quick points about the budget for the next advertising campaign.'),
-- Đoạn 7: Questions 162-165 (E-mail)
(11, 7, 'To: amal.abboud@bunzifoundation.org\nFrom: maria_mcfarland@myemail.com\nDate: Thursday, August 22\nSubject: Project Coordinator Position\nAttachment: résumé_m.mcfarland.pdf\n\nDear Mr. Abboud,\nMy friend Josiah Wilkins told me that you are seeking a project coordinator for your company. I have a degree in business administration and am attaching my résumé as I think I am an excellent fit for your needs. As you will see, I have experience using several cloud-based project-management programs. Furthermore, my organizational skills enable me to coordinate multiple activities simultaneously, and I can convey expectations clearly to team members involved in each phase of a project.\n\nMy current role as project coordinator for an international engineering firm, where I have worked for the past five years, has also afforded me ample experience managing teams, schedules, and budgets. While I enjoy the kind of work I do, it has become clear to me that I need motivation from a strong mission. The goal of your company to create sustainable housing projects is something that I strongly support and would be delighted to work on.\n\nThrough my work and volunteer activities, I have spent many months abroad in various countries throughout Asia and the Middle East. This seems particularly relevant to mention, as I am comfortable leading geographically and culturally diverse teams.\n\nThank you for your attention, and I look forward to speaking with you soon.\n\nKind regards,\nMaria McFarland'),
-- Đoạn 8: Questions 166-168 (Web page)
(12, 7, 'https://trexdale.com/aboutus\n\nAbout Our Company\n\nTrexdale Supply specializes in designing, producing, and installing furniture for all types of scientific laboratories. We provide a range of fully assembled cabinets, workstations, benches, and more, all made exclusively at our production facility in Dallas, Texas. Our lab furniture is available in a wide variety of sizes and configurations to match the needs of any research application.\n\nOur business offers products as well as design-consulting services. For start-up labs, we have a team of consulting specialists available to evaluate your facility\'s specific needs and assist you in arranging your space and choosing the most suitable furniture. Recently, for example, we were chosen by a major producer of biofuels to provide expert help in changing the layout of a research laboratory to maximize available space. As a result of this project, this client has realized substantial savings by reducing energy usage in the lab.\n\nPlease visit the "Lab Planning" section of this Web site if you are interested in learning more about building or renovating a laboratory facility. There, you can fill out an interest form to contact one of our consultants about your next project.'),
-- Đoạn 9: Questions 169-171 (Job advertisement)
(13, 7, 'PRODUCT DEMONSTRATORS NEEDED!\n\nAre you outgoing and enthusiastic? - [1] -. Do you enjoy talking to all types of people? Put your personality and communication skills to work! - [2] -. BBD Staffing is seeking to hire in-store product demonstrators to promote our clients\' merchandise to shoppers. - [3] -. As a member of our team, you will demonstrate a wide range of small kitchen appliances and tools in grocery stores and other retail venues.\n\nFor some products, you will be required to prepare simple recipes. You will also need to answer shoppers\' questions. Thus, it is essential that you can become familiar with clients\' products and provide key information to consumers. Because many of the demonstrations require working with food, candidates must have a Professional Food Handler certificate. - [4] -.\n\nTo apply, upload a video of no more than one minute in length telling us why you would be a successful product demonstrator at www.bbdstaffing.com/applications.'),
-- Đoạn 10: Questions 172-175 (Article)
(14, 7, 'Gorman Unveils Newest Smartphone Model\n\nLONDON (20 April) - Gorman Mobile unveiled its newest smartphone to an eager reception at the annual Technobrit Conference. The Pro Phone 4, which includes 512 GB of storage, a 7-inch screen display, and an optional stylus pen, will hit the shelves on 11 June. Unlike its predecessor - the Pro Phone 3 - it features a larger screen, an ultrawide camera lens, and 8K-resolution filming capability. - [1] -. The £999 starting price is £100 more than that of the previous model. Add-ons, such as the stylus pen, protective case, and wireless headphones, cost an additional £39, £59, and £79, respectively. Gorman Product Manager Ian Hill doesn\'t believe the price increase will dissuade customers. - [2] -.\n\n"The Pro Phone 4 is a game changer in terms of its picture quality and sleek design," said Hill. "Improvements were based on direct customer feedback, which cited the poor camera functionality as the biggest drawback of prior models. Our clients spoke, and we listened and adapted accordingly." - [3] -.\n\nOne similarity that the Pro Phone 4 has with previous models is the charger. Going against the trend of competing wireless companies, Gorman is instead focusing on convenience.\n\n"We want to afford our customers the ability to reuse elements of the other Gorman devices they\'ve already purchased," said Hill. "Why add to the overload of cables already in circulation?" - [4] -.'),
-- Đoạn 11: Questions 176-180 (Double Passage)
(15, 7, 'WORK ORDER: 7549\nRequester: Xi, Gina\nDate Entered: Wednesday, 9 April\nDate Due: Thursday, 10 April\nType: Technology end-user request\nSummary: Voice-mail security settings\nTechnician Assigned: Arnold, Sam\nComputer Workstation ID: HYS31\nDescription: Is it possible to remove the new layers of security on my voice mail in the new phone system? I really don\'t want to use a password, and I certainly don\'t want to change it every month. I don\'t need a high degree of security because my work is not confidential. If someone else gained access to my messages, it wouldn\'t do much harm.\n\n---\n\nTo: Gina Xi\nFrom: Sam Arnold\nDate: Thursday, 10 April\nSubject: Tech support request 7549\n\nHello, Ms. Xi,\nThis is in reference to your work order 7549 related to the new phone system. I am happy to help you with that. I understand that you do not feel that a high degree of security is needed for your voice-mail settings, but the new system does require you to have a password to retrieve your voice mail. However, company policy allows me to change the settings for employees who do not work with confidential material. I can update the security settings so that you do not have to reset the password on a regular basis.\n\nI want to make sure that you understand the risk involved with a lower level of security. Anyone who gains access to your voice-mail account can do more than simply listen to your messages. They would be able to delete messages, change your greeting, or change your password so that you would lose access to your own voice mail (at least until someone here at IT could override the password change). If you still feel comfortable with that level of risk, let me know, and I will change the settings so that your password never expires.\n\nSam Arnold\nTech Support Associate'),
-- Đoạn 12: Questions 181-185 (Double Passage)
(16, 7, 'To: Linda Hanshu\nFrom: Cliff Merson\nSubject: Lighting Issue\nDate: September 4, 10:12 A.M.\n\nHi, Ms. Hanshu:\nI want to check on the issue we discussed about lighting in the latest chapter of Titan Adventure. In past versions of the game, getting the reflections and lighting in green and blue areas correct has been a particular challenge, and it was a problem that kept arising. As the new release, Neptune\'s Voyage, is primarily an underwater adventure, addressing this problem is crucial. You said you would take charge of this, and I hope to hear that you have found a solution to the problem. The team was hoping to have one last rendering of the lighting for the game by October 10 for a preliminary run-through. Will the final version of the lighting be ready by then?\n\nAll other aspects of the game are on schedule. Please send me an update about the lighting at your earliest convenience.\n\nRegards,\nCliff Merson\nProject Manager, Rimerko Games\n\n---\n\nReview of Titan Adventure: Neptune\'s Voyage\nBy Leo Weber, April 1\n\nThis new installment of Titan Adventure will surprise and delight both new players and old aficionados long familiar with the series. Though open-world formats have been widespread in recent years, Neptune\'s Voyage brings something new to the format. By stripping down instructional guides, the game gives users the opportunity to discover new areas and devices. In Neptune\'s Voyage, you wake up as Thetis, a dolphin that is tasked with rescuing Neptune from an underwater cave. Users then climb, run, ride, sail, and fly through the world of the game, encountering new towns, ruins, and other creatures along the way. Some of these creatures will be familiar to longtime fans, but there is plenty of novelty as well. This newest version also corrects the green and blue image rendering that was sometimes a problem in earlier installments of Titan Adventure.\n\nNeptune\'s Voyage launches May 5 on Rimerko Clutch and FS5. It is available in English, Korean, Japanese, French, and Spanish.'),
-- Đoạn 13: Questions 186-190 (Triple Passage)
(17, 7, 'Wonder Ridge Radio Broadcast Schedule, Monday-Friday\n\n• 6 A.M.-Noon: COFFEE BREAK (Local news and interviews with community members) | Host: Felice Finney\n• Noon-4 P.M.: AFTERNOON JAZZ (Music from traditional jazz to jazz fusion) | Host: Malachi Mzee\n• 4 P.M.-7 P.M.: FOLK FRENZY (Folk music from around the world) | Host: Penny Ariza\n• 7 P.M.-10 P.M.: JOSIE\'S JOINT (Modern sounds selected by our station\'s own music director) | Host: Josie Jones\n\n---\n\nTo: feedback@wonderridgeradio.org\nFrom: pfabre@sendmail.net\nSubject: My new radio station!\nDate: October 22\n\nTo the folks at Wonder Ridge Radio:\nAs I was driving last week, I got tired of listening to sports talk and turned the dial. Suddenly, my car was filled with a song that I hadn\'t heard in many years. It was traditional music from France, where my grandmother was born. She used to play that song when I was a child. I never expected to hear it on the radio here in Wonder Ridge. Thanks for this experience and for all your great programs.\n\nYour new fan,\nPierre Fabre\n\n---\n\nWonder Ridge Radio Job Opening: Programming Assistant\nPosted November 2\n\nJob Description\nThe programming assistant reports to the director of programming and supports the radio station by performing a variety of research and communication functions. This role is an entry-level, part-time position.\n\nResponsibilities\n• Conducting background research on interviewees\n• Keeping up-to-date on news and news makers in order to suggest potential topics and guests for on-air interviews\n• Updating the station\'s Web site and program host biography pages\n• Using scheduling software to update the broadcast schedule\n• Communicating with listeners, especially via e-mail and social media\n\nTo apply, e-mail a résumé and cover letter to hiring@wonderridgeradio.org.'),
-- Đoạn 14: Questions 191-195 (Triple Passage)
(18, 7, 'Instructions for Requesting Records\nThank you for your interest in official records and documents maintained by the City of Abilene. To file a request for public information, please follow these steps.\n1. Create an account in the Records Center Web portal. Currently, all requests must be made through the portal.\n2. Use the drop-down menu to locate the department from which you are seeking information and submit your request. You will receive a confirmation e-mail with a reference number.\n3. The department staff will locate the requested records and contact you when they are available. You can have the records delivered to you, or you can pick them up in person. If you prefer to pick them up in person, you must make an appointment with the department staff.\n4. If there are any fees associated with your request, you will receive an itemized statement detailing the services provided and the charges for those specific services.\n\n---\n\nTo: Joo-Hee Park <jhpark@coa.net>\nFrom: Keith Brandenberg <kbrandenberg@mailcurrent.com>\nDate: May 3\nSubject: RE: Reference number W2486\n\nDear Ms. Park,\nThank you for confirming that my documents are available. I would like to pick them up in person as soon as possible. Do you have any appointments available this week?\n\nI have a question about the fee. Apparently, I am being charged $300 for my documents. I do not understand why the fee is so high, and there was no explanation included in your e-mail. I have requested records several times in the past in my role with RJ Environmental Engineering and have never paid such a high fee. In this case, I am only requesting two maps of the city\'s underground pipelines, which will inform our firm\'s current work advising the city on wastewater management.\n\nPlease clarify the fee for me, and let me know if I can pick up my documents this week. Thank you.\n\nBest regards,\nKeith Brandenberg\n\n---\n\nCity of Abilene Administrative Building\nVisitors must sign in prior to entering this facility. Please enter your name and the room you will visit in the logbook.\n\nFirst-Floor Directory:\nIT Services - Room 100\nParks and Recreation - Room 101\nTransportation - Room 102\nWastewater - Room 103'),
-- Đoạn 15: Questions 196-200 (Triple Passage)
(19, 7, 'Famous Actor, First Book\n\nLONDON (25 February) - Fans of Simon Eklund will be delighted with his autobiography, The Theatre Lights Dimmed, the first book he has written in his storied career as an actor. It provides wonderful insight into his career, starting with his first roles in cinema in his native Sweden, moving into his work in France and Italy, and finishing with his recent theatre work in the U.K.\n\nIn his book, Mr. Eklund dedicates a fair amount of text to discussing his mentor, Charles Gunnarsson, who helped him develop his skills early on in Stockholm. He also describes the difficulty of transitioning into different types of roles, especially from comedic to dramatic acting. He includes several funny anecdotes about his first attempts at acting onstage here in London. He describes them as disastrous, but anyone who saw his recent performance in Life and Games would say just the opposite.\n\nMr. Eklund has long been a captivating actor on stage and screen, and now he is a thoroughly engaging author.\n—Uma Joshi\n\n---\n\nTo: Edith Hocking\nFrom: Uma Joshi\nDate: 2 March\nSubject: RE: Opportunity\n\nDear Edith,\nThank you for agreeing to arrange an interview with Mr. Eklund for me. I think this will be a great follow-up to my recent piece.\n\nIn a helpful coincidence, I will be visiting his home country next month to address a journalists\' convention. I am the featured speaker and will discuss the benefits of diversity in journalism. I\'m sure we can set up something with Mr. Eklund just before or after my speech.\n\nBest,\nUma Joshi\nArts and Culture Editor\nTop News U.K.\n\n---\n\nTo: Uma Joshi <ujoshi@topnews.co.uk>\nFrom: Maria Cazalla <mcazalla@zephyrmail.se>\nDate: 20 March\nSubject: RE: Information\n\nDear Ms. Joshi,\nWe are all very excited about your interview next month with Mr. Eklund. He enjoys all your writing for Top News U.K.—the news stories, interviews, and, of course, your recent article about The Theatre Lights Dimmed!\n\nI just wanted to finalize a few details with you. We have arranged transportation for you from your hotel to Mr. Eklund\'s house and then back to the hotel. Please let me know how many people there will be in your group, because Mr. Eklund would like you all to stay for lunch.\n\nSincerely,\nMaria Cazalla');

-- 54 Câu hỏi trắc nghiệm của Part 7 (147 - 200)
INSERT INTO question (question_number, content, option_a, option_b, option_c, option_d, correct_option, explanation, part_id, question_group_id) VALUES
-- Đoạn 1 (147 - 148, group 5)
(147, 'What is indicated about Harbis Stationery Store?', 'It provides materials for students.', 'It has stores in multiple locations.', 'It is celebrating an anniversary.', 'It provides free shipping for online orders.', 'A', 'Bài quảng cáo có mục "All school supplies 10% off" (Tất cả đồ dùng học tập giảm 10%), chứng tỏ cửa hàng cung cấp vật dụng cho học sinh, sinh viên.', 7, 5),
(148, 'What item is discounted by the greatest percentage?', 'Box of ten cards', 'Box of five invitations', 'Wireless mouse', 'Desk lamp', 'B', '"Box of five customizable seasonal cards or invitations" được giảm 50%, tỷ lệ giảm giá lớn nhất so với 25% và 10%.', 7, 5),
-- Đoạn 2 (149 - 150, group 6)
(149, 'What is the purpose of the e-mail?', 'To inquire about leasing a vehicle', 'To inform a customer of required car maintenance', 'To announce the release of a new car', 'To register a used car for an extended warranty', 'B', 'Mục đích e-mail nêu rõ: "Your car is now due for its required annual service and maintenance check" (Xe của bạn đã đến hạn bảo dưỡng định kỳ bắt buộc).', 7, 6),
(150, 'What is indicated about Chen Construction?', 'It performs the servicing of its company vehicles.', 'It has a new project beginning March 1.', 'It provides leased cars to some employees.', 'It will soon begin a construction project for Toshi Auto Group.', 'C', 'Đoạn đầu e-mail nêu: "...service needs for cars leased by employees of Chen Construction" (bảo dưỡng cho xe mà nhân viên Chen Construction thuê).', 7, 6),
-- Đoạn 3 (151 - 153, group 7)
(151, 'What is the main purpose of the article?', 'To promote a new line of cookware', 'To advertise an orchestra concert', 'To announce a new series of books', 'To provide a calendar of local events', 'C', 'Bài báo thông báo Tillford Press ra mắt nhánh xuất bản mới (new imprint) Tillford Exalt với các đầu sách về lối sống lành mạnh, hồi ký...', 7, 7),
(152, 'What is planned for December?', 'An awards ceremony', 'The publication of a life story', 'The release of a new album', 'The launch of a celebrity\'s restaurant', 'B', 'Bài viết nói về hồi ký của Lain Lai: "Ms. Lai\'s story of her life and career will be the first to be launched. It is set for release in December."', 7, 7),
(153, 'What does Frederick Bissett emphasize about Tillford Exalt?', 'Its record-breaking sales', 'Its roots in Manchester', 'Its focus on fiction and poetry', 'Its broad range of authors', 'D', 'Ông Frederick Bissett nhấn mạnh: "We wanted authors from a wide variety of cultural backgrounds... not always famous", tức đa dạng các tác giả.', 7, 7),
-- Đoạn 4 (154 - 155, group 8)
(154, 'What problem does Mr. Skagen mention?', 'Some new employees are absent.', 'Some boxes are incorrectly labeled.', 'A package delivery is delayed.', 'An access door is malfunctioning.', 'D', 'Ông Skagen báo rằng: "the power door at Loading Dock B is acting up... raises all the way up but then drops back down", tức cửa tự động bị hỏng/trục trặc.', 7, 8),
(155, 'At 9:02 A.M., what does Mr. Skagen most likely mean when he writes, "Yes, that works"?', 'An electrician has arrived at a work site.', 'Some equipment is operating smoothly.', 'Trainees can help with some shipments.', 'Ms. Sadauskas is well suited for her job.', 'C', 'Skagen đồng ý với đề xuất của Brenda: đưa thực tập sinh sang khu vực của cô để học tạo nhãn và đóng gói đơn hàng buổi sáng.', 7, 8),
-- Đoạn 5 (156 - 157, group 9)
(156, 'Why was the form submitted?', 'An image is not displaying clearly.', 'A projector needs to be set up.', 'Audio is not functioning properly.', 'A microphone needs to be repaired.', 'C', 'Trong phần mô tả: "There is a problem with the television audio... the image was fine, but I could not hear anything" (Âm thanh TV không hoạt động).', 7, 9),
(157, 'What is Ms. Deckow planning to do next week?', 'Visit a client site', 'Deliver a product', 'Create an online video', 'Give a presentation', 'D', 'Cô ấy viết: "I\'m supposed to deliver a product demonstration for a client in room 500 next Monday" (Thực hiện buổi thuyết trình/giới thiệu sản phẩm cho khách hàng).', 7, 9),
-- Đoạn 6 (158 - 161, group 10)
(158, 'At what time will the executive board meeting begin?', '2:00 P.M.', '2:15 P.M.', '2:30 P.M.', '3:00 P.M.', 'C', 'Stef và Daniel đều nhắc tới việc họ phải tham dự cuộc họp ban điều hành vào lúc 2:30 ("different meeting at 2:30", "executive board meeting").', 7, 10),
(159, 'In what area does Mr. Iverman most likely work?', 'Marketing', 'Finance', 'Advertising', 'Executive management', 'B', 'Bill Iverman đề cập: "The quarterly reports just came in, and Daniel, Stef, and I need to review them", trong ngữ cảnh tìm người từ phòng tài chính (finance team).', 7, 10),
(160, 'Why does Ms. Glatt want a colleague to attend a meeting?', 'To summarize a previous meeting', 'To explain a promotional campaign', 'To provide information about a budget', 'To review recently approved documents', 'C', 'Ella Glatt chốt lại: "We just need one of you to clarify a few quick points about the budget for the next advertising campaign" (Làm rõ ngân sách).', 7, 10),
(161, 'At 11:43 A.M., what does Ms. Glatt most likely mean when she writes, "Sounds great"?', 'She accepts Mr. Seidal\'s offer.', 'She agrees that Mr. Iverman should attend the meeting at 3:00 P.M.', 'She is pleased with the proposed budget.', 'She is happy that a project has been completed.', 'A', 'Daniel Seidal đề nghị tham gia 15 phút từ 2:00 đến 2:15, và Ella chấp nhận đề nghị đó ("Sounds great").', 7, 10),
-- Đoạn 7 (162 - 165, group 11)
(162, 'What does Ms. McFarland mention about Mr. Wilkins?', 'He informed her of a job opening.', 'He will require a professional reference.', 'He would make a good business partner.', 'He is considering resigning from his position.', 'A', 'Maria viết: "My friend Josiah Wilkins told me that you are seeking a project coordinator for your company" (Bạn cô ấy thông báo về vị trí tuyển dụng).', 7, 11),
(163, 'The word "convey" in paragraph 1, line 5, is closest in meaning to', 'transport', 'communicate', 'recommend', 'adapt', 'B', '"Convey expectations clearly to team members" nghĩa là truyền đạt, giao tiếp rõ ràng ("communicate").', 7, 11),
(164, 'Why does Ms. McFarland want to leave her current position?', 'She wants a higher salary for her efforts.', 'She wants to work with a more experienced team.', 'She wants more opportunities for advancement.', 'She wants a role that inspires her more.', 'D', 'Maria chia sẻ: "it has become clear to me that I need motivation from a strong mission... create sustainable housing projects", cô muốn một công việc truyền cảm hứng hơn.', 7, 11),
(165, 'Why does Ms. McFarland mention her travels?', 'To request a placement in a particular country', 'To discuss how she came to acquire strategic industry contacts', 'To explain how she became aware of certain world issues', 'To emphasize her experience with people of different backgrounds', 'D', 'Cô ấy đề cập việc đi nhiều nước châu Á và Trung Đông để nhấn mạnh: "I am comfortable leading geographically and culturally diverse teams".', 7, 11),
-- Đoạn 8 (166 - 168, group 12)
(166, 'What does Trexdale Supply make?', 'Medical supplies', 'Farming equipment', 'Cabinets and furniture', 'Glass laboratory equipment', 'C', 'Ngay đoạn đầu: "Trexdale Supply specializes in designing, producing, and installing furniture for all types of scientific laboratories... cabinets, workstations, benches".', 7, 12),
(167, 'What did Trexdale Supply do in a recent project?', 'It reorganized a client\'s laboratory.', 'It converted its vehicles to use biofuels.', 'It expanded staffing at its production facility.', 'It helped a client organize a trade show.', 'A', 'Dự án gần đây: "provide expert help in changing the layout of a research laboratory to maximize available space" (sắp xếp lại bố cục phòng thí nghiệm).', 7, 12),
(168, 'What method of communicating with Trexdale Supply is mentioned?', 'By e-mail', 'By phone', 'By instant message', 'By an online form', 'D', 'Đoạn cuối hướng dẫn: "fill out an interest form to contact one of our consultants about your next project" (điền mẫu biểu trực tuyến).', 7, 12),
-- Đoạn 9 (169 - 171, group 13)
(169, 'What work experience would best qualify a candidate for the position?', 'Cook', 'Cashier', 'Interior designer', 'Event planner', 'A', 'Mô tả công việc yêu cầu: "prepare simple recipes... working with food, candidates must have a Professional Food Handler certificate", phù hợp nhất với kinh nghiệm nấu ăn (Cook).', 7, 13),
(170, 'According to the advertisement, what should people interested in applying do next?', 'Respond to a survey', 'Arrange for an interview', 'Submit a recording', 'Provide references', 'C', 'Cách ứng tuyển: "upload a video of no more than one minute in length telling us why you would be a successful product demonstrator" (nộp đoạn video ghi hình).', 7, 13),
(171, 'In which of the positions marked [1], [2], [3], and [4] does the following sentence best belong?\n"Many of the world\'s best-known brands rely on our product demonstrators to generate positive impressions of their products."', '[1]', '[2]', '[3]', '[4]', 'C', 'Câu văn bổ trợ trực tiếp cho câu giới thiệu về BBD Staffing ở vị trí [3]: thuê nhân viên trình diễn sản phẩm để quảng bá cho các thương hiệu khách hàng.', 7, 13),
-- Đoạn 10 (172 - 175, group 14)
(172, 'What is the purpose of the article?', 'To promote a technology show', 'To introduce a product', 'To interview smartphone users', 'To announce a recall of a device', 'B', 'Bài báo giới thiệu mẫu điện thoại thông minh mới của Gorman: "Gorman Mobile unveiled its newest smartphone... The Pro Phone 4".', 7, 14),
(173, 'How much do the Gorman Pro Phone 4 wireless headphones cost?', '£39', '£59', '£79', '£100', 'C', 'Bài viết liệt kê phụ kiện: "stylus pen, protective case, and wireless headphones, cost an additional £39, £59, and £79, respectively" -> tai nghe không dây là £79.', 7, 14),
(174, 'What does the Pro Phone 4 have in common with prior models?', 'The screen size', 'The camera resolution', 'The price', 'The charger', 'D', 'Điểm giống nhau được nêu rõ: "One similarity that the Pro Phone 4 has with previous models is the charger" (bộ sạc).', 7, 14),
(175, 'In which of the positions marked [1], [2], [3] and [4] does the following sentence best belong?\n"These upgrades do come at a cost."', '[1]', '[2]', '[3]', '[4]', 'A', 'Câu này nối giữa việc liệt kê các tính năng nâng cấp (màn hình lớn, camera góc siêu rộng, 8K) và câu thông báo giá tăng: "The £999 starting price is £100 more than that of the previous model".', 7, 14),
-- Đoạn 11 (176 - 180, group 15)
(176, 'What does Ms. Xi\'s request indicate about the company?', 'It provides mobile phones to some employees.', 'Its employees value confidentiality.', 'It has recently changed its phone system.', 'It offers technology training to employees.', 'C', 'Cả phiếu yêu cầu lẫn thư phản hồi đều nhắc đến hệ thống điện thoại mới: "the new phone system" (công ty vừa thay đổi hệ thống điện thoại).', 7, 15),
(177, 'In the e-mail, the word "regular" in paragraph 1, line 6, is closest in meaning to', 'periodic', 'orderly', 'customary', 'legitimate', 'A', '"On a regular basis" mang ý nghĩa định kỳ theo chu kỳ thời gian ("periodic").', 7, 15),
(178, 'Where did Mr. Arnold learn about the details of Ms. Xi\'s request?', 'In a weekly managers\' meeting', 'In a work order', 'In a phone call', 'In a personal voice mail', 'B', 'Arnold mở đầu thư: "This is in reference to your work order 7549 related to the new phone system" (từ phiếu yêu cầu công việc).', 7, 15),
(179, 'How does Mr. Arnold try to satisfy Ms. Xi\'s request?', 'By agreeing to everything Ms. Xi asked for', 'By resetting the password on Ms. Xi\'s phone', 'By referring the matter to another technician', 'By proposing to fulfill only part of Ms. Xi\'s request', 'D', 'Ms. Xi muốn bỏ hoàn toàn mật khẩu và không đổi hàng tháng, nhưng Arnold giải thích hệ thống bắt buộc phải có mật khẩu, ông chỉ có thể đáp ứng việc đặt mật khẩu không bao giờ hết hạn (đáp ứng một phần).', 7, 15),
(180, 'What does Mr. Arnold ask Ms. Xi to do?', 'Make the needed changes to her voice-mail system', 'Attend training about the new voice-mail system', 'Confirm that she wants him to change her voice-mail system', 'Provide a clear description of the problem with her voice-mail system', 'C', 'Arnold yêu cầu: "If you still feel comfortable with that level of risk, let me know, and I will change the settings..." (xác nhận đồng ý chấp nhận rủi ro).', 7, 15),
-- Đoạn 12 (181 - 185, group 16)
(181, 'In the e-mail, what is suggested about Mr. Merson?', 'He coordinates a game development team.', 'He is convinced that Titan Adventure is overpriced.', 'He is a new employee at Rimerko Games.', 'He will leave on a business trip on October 10.', 'A', 'Chữ ký của Cliff Merson là "Project Manager, Rimerko Games" và nội dung điều phối tiến độ của nhóm phát triển game.', 7, 16),
(182, 'In the review, what is indicated about Neptune\'s Voyage?', 'It is a major competitor of Titan Adventure.', 'It features an open-world format.', 'It is the first video game in a series.', 'It is Rimerko\'s most challenging game.', 'B', 'Bài đánh giá nêu: "Though open-world formats have been widespread in recent years, Neptune\'s Voyage brings something new to the format".', 7, 16),
(183, 'What can be concluded about Ms. Hanshu?', 'She wrote the script for Neptune\'s Voyage.', 'She successfully addressed Mr. Merson\'s concern.', 'She won an award for game design.', 'She is a project manager.', 'B', 'Merson lo lắng về việc hiển thị màu xanh lá và xanh dương, và bài review xác nhận phiên bản mới này đã sửa thành công lỗi đó: "This newest version also corrects the green and blue image rendering".', 7, 16),
(184, 'What does Mr. Weber find exciting about Neptune\'s Voyage?', 'It has players act in the role of Neptune.', 'It uses lighting to show players where to navigate.', 'It introduces a completely new set of characters.', 'It lets players explore new features without guidance.', 'D', 'Weber ấn tượng với: "By stripping down instructional guides, the game gives users the opportunity to discover new areas and devices" (khám phá không cần hướng dẫn).', 7, 16),
(185, 'When will Neptune\'s Voyage be available?', 'On September 4', 'On October 10', 'On April 1', 'On May 5', 'D', 'Câu kết bài đánh giá ghi rõ: "Neptune\'s Voyage launches May 5 on Rimerko Clutch and FS5".', 7, 16),
-- Đoạn 13 (186 - 190, group 17)
(186, 'According to the schedule, who is Ms. Jones?', 'The advertising manager at a radio station', 'The host of a community news program', 'The music director at Wonder Ridge Radio', 'The host of a sports radio program', 'C', 'Trong lịch phát sóng mục 7 P.M.-10 P.M.: "selected by our station\'s own music director | Host: Josie Jones".', 7, 17),
(187, 'What is the purpose of the e-mail?', 'To express praise for the radio station', 'To ask about job opportunities', 'To request more sports talk show programming', 'To inquire about the name of a song', 'A', 'Pierre Fabre viết thư để cảm ơn và khen ngợi đài phát thanh: "Thanks for this experience and for all your great programs. Your new fan...".', 7, 17),
(188, 'When did Mr. Fabre most likely first listen to Wonder Ridge Radio?', 'Between 6 A.M. and noon', 'Between noon and 4 P.M.', 'Between 4 P.M. and 7 P.M.', 'Between 7 P.M. and 10 P.M.', 'C', 'Ông nghe thấy "traditional music from France". Theo lịch, chương trình phát nhạc dân gian thế giới (Folk music from around the world) là FOLK FRENZY từ 4 P.M. đến 7 P.M.', 7, 17),
(189, 'What does the job advertisement suggest applicants must have?', 'A willingness to travel', 'Familiarity with computers', 'A degree in communications', 'Extensive experience in the radio industry', 'B', 'Mô tả công việc yêu cầu: "Updating the station\'s Web site... Using scheduling software...", đòi hỏi kỹ năng sử dụng máy tính thành thạo.', 7, 17),
(190, 'What radio program will probably receive the most support from the programming assistant?', 'Coffee Break', 'Afternoon Jazz', 'Folk Frenzy', 'Josie\'s Joint', 'A', 'Nhiệm vụ gồm "Conducting background research on interviewees... topics and guests for on-air interviews", phù hợp nhất với COFFEE BREAK (Local news and interviews with community members).', 7, 17),
-- Đoạn 14 (191 - 195, group 18)
(191, 'What do the instructions indicate about records requests?', 'They can be made only on certain days.', 'They can be made only online.', 'They can be filed only by authorized personnel.', 'They can be filed only after a fee is paid.', 'B', 'Mục 1 của hướng dẫn nêu rõ: "Currently, all requests must be made through the portal" (chỉ gửi yêu cầu qua cổng trực tuyến).', 7, 18),
(192, 'According to the e-mail, how does Mr. Brandenberg plan to use some public information?', 'To add information to a Web portal', 'To help his company advise the city', 'To identify an accounting error', 'To learn how an agency is structured', 'B', 'Brandenberg giải thích tài liệu này sẽ: "inform our firm\'s current work advising the city on wastewater management" (phục vụ việc tư vấn cho thành phố về xử lý nước thải).', 7, 18),
(193, 'What does the sign indicate visitors must do before entering a building?', 'Go through a security screening', 'Get a parking permit', 'Present some identification', 'Sign a logbook', 'D', 'Bảng chỉ dẫn ghi: "Visitors must sign in prior to entering this facility. Please enter your name and the room you will visit in the logbook" (ký vào sổ ghi danh).', 7, 18),
(194, 'What was Mr. Brandenberg expecting to receive?', 'An itemized statement of fees', 'A letter from his company', 'A phone call from a city official', 'A password for the Web portal', 'A', 'Theo mục 4 hướng dẫn, người yêu cầu sẽ nhận bảng kê chi tiết lệ phí ("itemized statement detailing the services..."). Brandenberg thắc mắc vì không nhận được lời giải thích nào cho khoản phí $300.', 7, 18),
(195, 'What room will Mr. Brandenberg most likely visit?', 'Room 100', 'Room 101', 'Room 102', 'Room 103', 'D', 'Brandenberg làm việc liên quan đến quản lý nước thải ("wastewater management"). Trong danh bạ tầng 1, phòng Wastewater là Room 103.', 7, 18),
-- Đoạn 15 (196 - 200, group 19)
(196, 'What does the review mention about Mr. Eklund?', 'He enjoys his work as a director.', 'He has been a mentor to many young people.', 'He is a well-known actor.', 'He has written many books.', 'C', 'Bài báo mô tả: "his storied career as an actor... captivating actor on stage and screen" (diễn viên nổi tiếng).', 7, 19),
(197, 'Where most likely will Ms. Joshi meet Mr. Eklund?', 'In Sweden', 'In France', 'In Italy', 'In the United Kingdom', 'A', 'Eklund sinh ra tại Thụy Điển ("his native Sweden"). Joshi viết rằng cô sẽ đến quê hương ông vào tháng tới ("visiting his home country next month") để phỏng vấn ông.', 7, 19),
(198, 'According to the first e-mail, what is one reason Ms. Joshi will travel in April?', 'To go on a vacation', 'To interview for a new job', 'To attend an international film festival', 'To speak at a conference', 'D', 'Joshi giải thích lý do chuyến đi: "address a journalists\' convention. I am the featured speaker" (phát biểu tại một hội nghị).', 7, 19),
(199, 'What is the purpose of the second e-mail?', 'To reserve a hotel room', 'To confirm meeting arrangements', 'To discuss an idea for a movie', 'To ask for transportation', 'B', 'Maria Cazalla gửi e-mail để: "finalize a few details with you. We have arranged transportation... Mr. Eklund would like you all to stay for lunch" (xác nhận lịch trình và sắp xếp buổi gặp).', 7, 19),
(200, 'What can be concluded about Mr. Eklund?', 'He hopes to write for a British news site.', 'He just hired a new assistant.', 'He was pleased with Ms. Joshi\'s review of his book.', 'He frequently cooks special meals.', 'C', 'E-mail thứ 2 cho biết: "He enjoys all your writing... and, of course, your recent article about The Theatre Lights Dimmed!" (ông ấy rất thích bài viết đánh giá của Joshi về cuốn sách).', 7, 19);

