package com.toeic.subscription.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionAllPropertiesEquals(Subscription expected, Subscription actual) {
        assertSubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertSubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionAllUpdatablePropertiesEquals(Subscription expected, Subscription actual) {
        assertSubscriptionUpdatableFieldsEquals(expected, actual);
        assertSubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionAutoGeneratedPropertiesEquals(Subscription expected, Subscription actual) {
        assertThat(actual)
            .as("Verify Subscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionUpdatableFieldsEquals(Subscription expected, Subscription actual) {
        assertThat(actual)
            .as("Verify Subscription relevant properties")
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartsAt()).as("check startsAt").isEqualTo(expected.getStartsAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriptionUpdatableRelationshipsEquals(Subscription expected, Subscription actual) {
        assertThat(actual)
            .as("Verify Subscription relationships")
            .satisfies(a -> assertThat(a.getPlan()).as("check plan").isEqualTo(expected.getPlan()));
    }
}
