package com.toeic.course.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChapterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChapterAllPropertiesEquals(Chapter expected, Chapter actual) {
        assertChapterAutoGeneratedPropertiesEquals(expected, actual);
        assertChapterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChapterAllUpdatablePropertiesEquals(Chapter expected, Chapter actual) {
        assertChapterUpdatableFieldsEquals(expected, actual);
        assertChapterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChapterAutoGeneratedPropertiesEquals(Chapter expected, Chapter actual) {
        assertThat(actual)
            .as("Verify Chapter auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChapterUpdatableFieldsEquals(Chapter expected, Chapter actual) {
        assertThat(actual)
            .as("Verify Chapter relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChapterUpdatableRelationshipsEquals(Chapter expected, Chapter actual) {
        assertThat(actual)
            .as("Verify Chapter relationships")
            .satisfies(a -> assertThat(a.getCourse()).as("check course").isEqualTo(expected.getCourse()));
    }
}
