package com.toeic.course.domain;

import static com.toeic.course.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CourseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseAllPropertiesEquals(Course expected, Course actual) {
        assertCourseAutoGeneratedPropertiesEquals(expected, actual);
        assertCourseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseAllUpdatablePropertiesEquals(Course expected, Course actual) {
        assertCourseUpdatableFieldsEquals(expected, actual);
        assertCourseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseAutoGeneratedPropertiesEquals(Course expected, Course actual) {
        assertThat(actual)
            .as("Verify Course auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseUpdatableFieldsEquals(Course expected, Course actual) {
        assertThat(actual)
            .as("Verify Course relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a ->
                assertThat(a.getDiscountPrice())
                    .as("check discountPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountPrice())
            )
            .satisfies(a -> assertThat(a.getThumbnailUrl()).as("check thumbnailUrl").isEqualTo(expected.getThumbnailUrl()))
            .satisfies(a -> assertThat(a.getLevel()).as("check level").isEqualTo(expected.getLevel()))
            .satisfies(a -> assertThat(a.getIsPublished()).as("check isPublished").isEqualTo(expected.getIsPublished()))
            .satisfies(a ->
                assertThat(a.getTotalDurationSeconds()).as("check totalDurationSeconds").isEqualTo(expected.getTotalDurationSeconds())
            )
            .satisfies(a -> assertThat(a.getTotalLessons()).as("check totalLessons").isEqualTo(expected.getTotalLessons()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseUpdatableRelationshipsEquals(Course expected, Course actual) {
        // empty method
    }
}
