package com.toeic.course.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CourseEnrollmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseEnrollmentAllPropertiesEquals(CourseEnrollment expected, CourseEnrollment actual) {
        assertCourseEnrollmentAutoGeneratedPropertiesEquals(expected, actual);
        assertCourseEnrollmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseEnrollmentAllUpdatablePropertiesEquals(CourseEnrollment expected, CourseEnrollment actual) {
        assertCourseEnrollmentUpdatableFieldsEquals(expected, actual);
        assertCourseEnrollmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseEnrollmentAutoGeneratedPropertiesEquals(CourseEnrollment expected, CourseEnrollment actual) {
        assertThat(actual)
            .as("Verify CourseEnrollment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseEnrollmentUpdatableFieldsEquals(CourseEnrollment expected, CourseEnrollment actual) {
        assertThat(actual)
            .as("Verify CourseEnrollment relevant properties")
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getEnrolledAt()).as("check enrolledAt").isEqualTo(expected.getEnrolledAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseEnrollmentUpdatableRelationshipsEquals(CourseEnrollment expected, CourseEnrollment actual) {
        assertThat(actual)
            .as("Verify CourseEnrollment relationships")
            .satisfies(a -> assertThat(a.getCourse()).as("check course").isEqualTo(expected.getCourse()));
    }
}
