package com.toeic.notification.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificationTemplateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationTemplateAllPropertiesEquals(NotificationTemplate expected, NotificationTemplate actual) {
        assertNotificationTemplateAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationTemplateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationTemplateAllUpdatablePropertiesEquals(NotificationTemplate expected, NotificationTemplate actual) {
        assertNotificationTemplateUpdatableFieldsEquals(expected, actual);
        assertNotificationTemplateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationTemplateAutoGeneratedPropertiesEquals(NotificationTemplate expected, NotificationTemplate actual) {
        assertThat(actual)
            .as("Verify NotificationTemplate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationTemplateUpdatableFieldsEquals(NotificationTemplate expected, NotificationTemplate actual) {
        assertThat(actual)
            .as("Verify NotificationTemplate relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getChannel()).as("check channel").isEqualTo(expected.getChannel()))
            .satisfies(a -> assertThat(a.getSubject()).as("check subject").isEqualTo(expected.getSubject()))
            .satisfies(a -> assertThat(a.getBodyTemplate()).as("check bodyTemplate").isEqualTo(expected.getBodyTemplate()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationTemplateUpdatableRelationshipsEquals(NotificationTemplate expected, NotificationTemplate actual) {
        // empty method
    }
}
