configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzYzZTc5YzQxMGFlZmRkOTFlZmY3ZjZlNmEyZTUwMzQxMjAzNDMwZmY0YWU0YjIzMGJjYTYzNzU3YWQ5NzNhZGQzZWJjMzg5NDI4ZWE1MjI4NGMyYTVlYzM2MDVmZmYxZjM5NjNiMjA0YzBjYTA4MDIwMDViY2ZiYjdlNzhhMTk=
