import { ExamItem } from '@/types/examList';

export const FALLBACK_EXAM_CARDS: ExamItem[] = [
  {
    id: '1',
    title: 'ToeicPro ETS Practice Test 01',
    description:
      'Đề thi chuẩn hóa đo lường năng lực tổng thể, phân bổ cân bằng giữa thư từ văn phòng, thông báo điều hành và hội thoại ngắn.',
    tag1: 'ETS 2026',
    tag1Type: 'standard',
    tag2: 'Mô phỏng đầy đủ',
    tag2Type: 'normal',
    durationMinutes: 120,
    totalQuestions: 200,
    takenCount: 48210,
    averageScore: 684,
    category: 'full',
    source: 'ETS Authentic',
    targetScore: '750+',
    status: 'untaken',
    audioAccents: 'Audio: 4 Giọng đọc',
    listeningQuestions: 100,
    readingQuestions: 100,
  },
  {
    id: '2',
    title: 'ToeicPro Advanced Challenge 02',
    description:
      'Thiết kế nâng cao vốn từ vựng học thuật trong Part 5 và các câu hỏi suy luận đa người nói phức tạp trong Part 3 và 4.',
    tag1: 'ETS 2026',
    tag1Type: 'standard',
    tag2: 'Độ khó cao',
    tag2Type: 'hard',
    durationMinutes: 120,
    totalQuestions: 200,
    takenCount: 34120,
    averageScore: 642,
    category: 'full',
    source: 'ETS Authentic',
    targetScore: '850+',
    status: 'in_progress',
    userProgress: '85/200',
    audioAccents: 'Target 850+',
    listeningQuestions: 100,
    readingQuestions: 100,
  },
  {
    id: '3',
    title: 'Economy Toeic Simulation Vol 1',
    description:
      'Tập trung chuyên sâu vào giao tiếp doanh nghiệp thực tế: sáp nhập công ty, kế hoạch thu mua và thông báo hậu cần thương mại.',
    tag1: 'Economy 2026',
    tag1Type: 'economy',
    tag2: 'Tiếng Anh Doanh nghiệp',
    tag2Type: 'normal',
    durationMinutes: 120,
    totalQuestions: 200,
    takenCount: 29880,
    averageScore: 715,
    category: 'full',
    source: 'Economy',
    targetScore: '750+',
    status: 'completed',
    userScore: 785,
    audioAccents: 'Độ chuẩn hóa cao',
    listeningQuestions: 100,
    readingQuestions: 100,
  },
  {
    id: '4',
    title: 'ETS Official Speed Sprint 03',
    description:
      'Bộ đề thi rút gọn kiểm tra phản xạ nhanh trong 50 câu hỏi trọng điểm, thích hợp cho việc đánh giá nhanh trình độ hiện tại.',
    tag1: 'ETS 2026',
    tag1Type: 'standard',
    tag2: 'Thịnh hành',
    tag2Type: 'popular',
    durationMinutes: 35,
    totalQuestions: 50,
    takenCount: 52430,
    averageScore: 370,
    category: 'mini',
    source: 'ETS Authentic',
    targetScore: '550+',
    status: 'untaken',
    audioAccents: 'Cập nhật T11/2025',
    listeningQuestions: 25,
    readingQuestions: 25,
  },
  {
    id: '5',
    title: 'Listening Mastery Sprint 04',
    description:
      'Bài luyện nghe cường độ cao. Tích hợp tạp âm môi trường thực tế, người nói ngắt lời và câu hỏi suy luận phản xạ tức thì.',
    tag1: 'Chuyên Sâu Nghe',
    tag1Type: 'special',
    tag2: 'Part 1–4',
    tag2Type: 'normal',
    durationMinutes: 45,
    totalQuestions: 100,
    takenCount: 18900,
    averageScore: 395,
    category: 'listening',
    source: 'Hackers',
    targetScore: '850+',
    status: 'in_progress',
    userProgress: '40/100',
    audioAccents: 'Mục tiêu LC 450+',
    listeningQuestions: 100,
    readingQuestions: 0,
  },
  {
    id: '6',
    title: 'Reading Speed & Grammar Vol 2',
    description:
      'Được hiệu chỉnh nghiêm ngặt để rèn luyện kỹ năng đọc lướt (skimming) và suy luận cấu trúc ngữ pháp trong áp lực thời gian.',
    tag1: 'Chuyên Sâu Đọc',
    tag1Type: 'special',
    tag2: 'Part 5–7',
    tag2Type: 'normal',
    durationMinutes: 75,
    totalQuestions: 100,
    takenCount: 21340,
    averageScore: 360,
    category: 'reading',
    source: 'Hackers',
    targetScore: '750+',
    status: 'completed',
    userScore: 720,
    audioAccents: 'Tốc độ: 45s/câu',
    listeningQuestions: 0,
    readingQuestions: 100,
  },
];
