package com.toeic.exam.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExamAttemptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamAttemptAllPropertiesEquals(ExamAttempt expected, ExamAttempt actual) {
        assertExamAttemptAutoGeneratedPropertiesEquals(expected, actual);
        assertExamAttemptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamAttemptAllUpdatablePropertiesEquals(ExamAttempt expected, ExamAttempt actual) {
        assertExamAttemptUpdatableFieldsEquals(expected, actual);
        assertExamAttemptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamAttemptAutoGeneratedPropertiesEquals(ExamAttempt expected, ExamAttempt actual) {
        assertThat(actual)
            .as("Verify ExamAttempt auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamAttemptUpdatableFieldsEquals(ExamAttempt expected, ExamAttempt actual) {
        assertThat(actual)
            .as("Verify ExamAttempt relevant properties")
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getListeningScore()).as("check listeningScore").isEqualTo(expected.getListeningScore()))
            .satisfies(a -> assertThat(a.getReadingScore()).as("check readingScore").isEqualTo(expected.getReadingScore()))
            .satisfies(a -> assertThat(a.getTotalScore()).as("check totalScore").isEqualTo(expected.getTotalScore()))
            .satisfies(a -> assertThat(a.getCorrectAnswers()).as("check correctAnswers").isEqualTo(expected.getCorrectAnswers()))
            .satisfies(a -> assertThat(a.getWrongAnswers()).as("check wrongAnswers").isEqualTo(expected.getWrongAnswers()))
            .satisfies(a -> assertThat(a.getSkippedAnswers()).as("check skippedAnswers").isEqualTo(expected.getSkippedAnswers()))
            .satisfies(a -> assertThat(a.getTimeSpentSeconds()).as("check timeSpentSeconds").isEqualTo(expected.getTimeSpentSeconds()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamAttemptUpdatableRelationshipsEquals(ExamAttempt expected, ExamAttempt actual) {
        assertThat(actual)
            .as("Verify ExamAttempt relationships")
            .satisfies(a -> assertThat(a.getExam()).as("check exam").isEqualTo(expected.getExam()));
    }
}
