package com.toeic.exam.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PartAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartAllPropertiesEquals(Part expected, Part actual) {
        assertPartAutoGeneratedPropertiesEquals(expected, actual);
        assertPartAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartAllUpdatablePropertiesEquals(Part expected, Part actual) {
        assertPartUpdatableFieldsEquals(expected, actual);
        assertPartUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartAutoGeneratedPropertiesEquals(Part expected, Part actual) {
        assertThat(actual)
            .as("Verify Part auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartUpdatableFieldsEquals(Part expected, Part actual) {
        assertThat(actual)
            .as("Verify Part relevant properties")
            .satisfies(a -> assertThat(a.getPartNumber()).as("check partNumber").isEqualTo(expected.getPartNumber()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getTotalQuestions()).as("check totalQuestions").isEqualTo(expected.getTotalQuestions()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartUpdatableRelationshipsEquals(Part expected, Part actual) {
        assertThat(actual)
            .as("Verify Part relationships")
            .satisfies(a -> assertThat(a.getExam()).as("check exam").isEqualTo(expected.getExam()));
    }
}
