package com.toeic.exam.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QuestionGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionGroupAllPropertiesEquals(QuestionGroup expected, QuestionGroup actual) {
        assertQuestionGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertQuestionGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionGroupAllUpdatablePropertiesEquals(QuestionGroup expected, QuestionGroup actual) {
        assertQuestionGroupUpdatableFieldsEquals(expected, actual);
        assertQuestionGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionGroupAutoGeneratedPropertiesEquals(QuestionGroup expected, QuestionGroup actual) {
        assertThat(actual)
            .as("Verify QuestionGroup auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionGroupUpdatableFieldsEquals(QuestionGroup expected, QuestionGroup actual) {
        assertThat(actual)
            .as("Verify QuestionGroup relevant properties")
            .satisfies(a -> assertThat(a.getPassageText()).as("check passageText").isEqualTo(expected.getPassageText()))
            .satisfies(a -> assertThat(a.getAudioUrl()).as("check audioUrl").isEqualTo(expected.getAudioUrl()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionGroupUpdatableRelationshipsEquals(QuestionGroup expected, QuestionGroup actual) {
        assertThat(actual)
            .as("Verify QuestionGroup relationships")
            .satisfies(a -> assertThat(a.getPart()).as("check part").isEqualTo(expected.getPart()));
    }
}
