package com.toeic.exam.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QuestionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionAllPropertiesEquals(Question expected, Question actual) {
        assertQuestionAutoGeneratedPropertiesEquals(expected, actual);
        assertQuestionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionAllUpdatablePropertiesEquals(Question expected, Question actual) {
        assertQuestionUpdatableFieldsEquals(expected, actual);
        assertQuestionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionAutoGeneratedPropertiesEquals(Question expected, Question actual) {
        assertThat(actual)
            .as("Verify Question auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionUpdatableFieldsEquals(Question expected, Question actual) {
        assertThat(actual)
            .as("Verify Question relevant properties")
            .satisfies(a -> assertThat(a.getQuestionNumber()).as("check questionNumber").isEqualTo(expected.getQuestionNumber()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()))
            .satisfies(a -> assertThat(a.getAudioUrl()).as("check audioUrl").isEqualTo(expected.getAudioUrl()))
            .satisfies(a -> assertThat(a.getOptionA()).as("check optionA").isEqualTo(expected.getOptionA()))
            .satisfies(a -> assertThat(a.getOptionB()).as("check optionB").isEqualTo(expected.getOptionB()))
            .satisfies(a -> assertThat(a.getOptionC()).as("check optionC").isEqualTo(expected.getOptionC()))
            .satisfies(a -> assertThat(a.getOptionD()).as("check optionD").isEqualTo(expected.getOptionD()))
            .satisfies(a -> assertThat(a.getCorrectOption()).as("check correctOption").isEqualTo(expected.getCorrectOption()))
            .satisfies(a -> assertThat(a.getExplanation()).as("check explanation").isEqualTo(expected.getExplanation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionUpdatableRelationshipsEquals(Question expected, Question actual) {
        assertThat(actual)
            .as("Verify Question relationships")
            .satisfies(a -> assertThat(a.getPart()).as("check part").isEqualTo(expected.getPart()))
            .satisfies(a -> assertThat(a.getQuestionGroup()).as("check questionGroup").isEqualTo(expected.getQuestionGroup()));
    }
}
