package com.toeic.exam.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserAnswerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAnswerAllPropertiesEquals(UserAnswer expected, UserAnswer actual) {
        assertUserAnswerAutoGeneratedPropertiesEquals(expected, actual);
        assertUserAnswerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAnswerAllUpdatablePropertiesEquals(UserAnswer expected, UserAnswer actual) {
        assertUserAnswerUpdatableFieldsEquals(expected, actual);
        assertUserAnswerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAnswerAutoGeneratedPropertiesEquals(UserAnswer expected, UserAnswer actual) {
        assertThat(actual)
            .as("Verify UserAnswer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAnswerUpdatableFieldsEquals(UserAnswer expected, UserAnswer actual) {
        assertThat(actual)
            .as("Verify UserAnswer relevant properties")
            .satisfies(a -> assertThat(a.getSelectedOption()).as("check selectedOption").isEqualTo(expected.getSelectedOption()))
            .satisfies(a -> assertThat(a.getIsCorrect()).as("check isCorrect").isEqualTo(expected.getIsCorrect()))
            .satisfies(a -> assertThat(a.getTimeSpentSeconds()).as("check timeSpentSeconds").isEqualTo(expected.getTimeSpentSeconds()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserAnswerUpdatableRelationshipsEquals(UserAnswer expected, UserAnswer actual) {
        assertThat(actual)
            .as("Verify UserAnswer relationships")
            .satisfies(a -> assertThat(a.getExamAttempt()).as("check examAttempt").isEqualTo(expected.getExamAttempt()))
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()));
    }
}
