package com.toeic.payment.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PaymentWebhookLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentWebhookLogAllPropertiesEquals(PaymentWebhookLog expected, PaymentWebhookLog actual) {
        assertPaymentWebhookLogAutoGeneratedPropertiesEquals(expected, actual);
        assertPaymentWebhookLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentWebhookLogAllUpdatablePropertiesEquals(PaymentWebhookLog expected, PaymentWebhookLog actual) {
        assertPaymentWebhookLogUpdatableFieldsEquals(expected, actual);
        assertPaymentWebhookLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentWebhookLogAutoGeneratedPropertiesEquals(PaymentWebhookLog expected, PaymentWebhookLog actual) {
        assertThat(actual)
            .as("Verify PaymentWebhookLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentWebhookLogUpdatableFieldsEquals(PaymentWebhookLog expected, PaymentWebhookLog actual) {
        assertThat(actual)
            .as("Verify PaymentWebhookLog relevant properties")
            .satisfies(a -> assertThat(a.getOrderCode()).as("check orderCode").isEqualTo(expected.getOrderCode()))
            .satisfies(a -> assertThat(a.getGateway()).as("check gateway").isEqualTo(expected.getGateway()))
            .satisfies(a -> assertThat(a.getRawPayload()).as("check rawPayload").isEqualTo(expected.getRawPayload()))
            .satisfies(a -> assertThat(a.getSignature()).as("check signature").isEqualTo(expected.getSignature()))
            .satisfies(a -> assertThat(a.getIsVerified()).as("check isVerified").isEqualTo(expected.getIsVerified()))
            .satisfies(a -> assertThat(a.getResponseCode()).as("check responseCode").isEqualTo(expected.getResponseCode()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentWebhookLogUpdatableRelationshipsEquals(PaymentWebhookLog expected, PaymentWebhookLog actual) {
        assertThat(actual)
            .as("Verify PaymentWebhookLog relationships")
            .satisfies(a ->
                assertThat(a.getPaymentTransaction()).as("check paymentTransaction").isEqualTo(expected.getPaymentTransaction())
            );
    }
}
